In [1]:
import pandas as pd
import glob
import os

In [2]:
author = pd.read_parquet("search-application/data/authorships_combined_2000_2024.parquet")
publication = pd.read_parquet("search-application/data/publication_combined_2000_2024.parquet")

In [3]:
author.columns

Index(['work_id', 'display_name', 'orcid', 'author_position',
       'is_corresponding', 'affiliations', 'affiliation_raw', 'author_id'],
      dtype='object')

In [4]:
publication.columns

Index(['work_id', 'title', 'display_name', 'abstract', 'doi',
       'publication_date', 'publication_year', 'cited_by_count', 'ids', 'type',
       'is_oa', 'source_display_name', 'source_id', 'issn_l',
       'host_organization', 'host_organization_name', 'landing_page_url',
       'pdf_url', 'license', 'version', 'topics', 'keywords', 'is_retracted',
       'grants'],
      dtype='object')

In [5]:
author.head()

,work_id,display_name,orcid,author_position,is_corresponding,affiliations,affiliation_raw,author_id
0,https://openalex.org/W2128158076,S. Agostinelli,None,first,False,"[{""inst_id"":""I83816512"",""display_name"":""Univer...","University of Genoa, Genoa, Italy",A5019950553
1,https://openalex.org/W2128158076,John E. Allison,0000-0003-4108-4709,middle,False,"[{""inst_id"":""I28407311"",""display_name"":""Univer...","University of Manchester, Manchester, United K...",A5102846098
2,https://openalex.org/W2128158076,B. R. Ko,0000-0002-4591-5269,middle,False,"[{""inst_id"":""I138728355"",""display_name"":""High ...","High Energy Accelerator Research Organization,...",A5009376065
3,https://openalex.org/W2128158076,J. Apostolakis,0000-0003-1184-3727,middle,False,"[{""inst_id"":""I67311998"",""display_name"":""Europe...","European Organization for Nuclear Research, Ge...",A5056196917
4,https://openalex.org/W2128158076,H. M. Araújo,0000-0002-5972-2783,middle,False,"[{""inst_id"":""I47508984"",""display_name"":""Imperi...","Imperial College London, London, United Kingdom",A5075976624

In [6]:
author['author_position'].unique()

array(['first', 'middle', 'last'], dtype=object)

In [7]:
publication.head()

,work_id,title,display_name,abstract,doi,publication_date,publication_year,cited_by_count,ids,type,...,host_organization,host_organization_name,landing_page_url,pdf_url,license,version,topics,keywords,is_retracted,grants
0,https://openalex.org/W2128158076,Geant4—a simulation toolkit,Geant4—a simulation toolkit,None,https://doi.org/10.1016/s0168-9002(03)01368-8,2003-06-21,2003,22300,"[""https://openalex.org/W2128158076"",""https://d...",article,...,https://openalex.org/P4310320990,Elsevier BV,https://doi.org/10.1016/s0168-9002(03)01368-8,None,None,None,"[{""i"":1,""score"":0.9969,""id"":""https://openalex....","[{""id"":""https://openalex.org/keywords/tracking...",False,None
1,https://openalex.org/W2125899728,Comparison of Multiobjective Evolutionary Algo...,Comparison of Multiobjective Evolutionary Algo...,"In this paper, we provide a systematic compari...",https://doi.org/10.1162/106365600568202,2000-06-01,2000,5352,"[""https://openalex.org/W2125899728"",""https://d...",article,...,https://openalex.org/P4310315718,The MIT Press,https://doi.org/10.1162/106365600568202,None,None,None,"[{""i"":1,""score"":0.9999,""id"":""https://openalex....",null,False,None
2,https://openalex.org/W2144476887,No health without mental health,No health without mental health,None,https://doi.org/10.1016/s0140-6736(07)61238-0,2007-09-01,2007,3567,"[""https://openalex.org/W2144476887"",""https://d...",review,...,https://openalex.org/P4310320990,Elsevier BV,https://doi.org/10.1016/s0140-6736(07)61238-0,None,None,None,"[{""i"":1,""score"":0.9964,""id"":""https://openalex....",null,False,None
3,https://openalex.org/W2101881391,A Randomized Trial of Letrozole in Postmenopau...,A Randomized Trial of Letrozole in Postmenopau...,"In hormone-dependent breast cancer, five years...",https://doi.org/10.1056/nejmoa032312,2003-11-06,2003,1803,"[""https://openalex.org/W2101881391"",""https://d...",letter,...,https://openalex.org/P4310320239,Massachusetts Medical Society,https://doi.org/10.1056/nejmoa032312,https://www.nejm.org/doi/pdf/10.1056/NEJMoa032...,None,publishedVersion,"[{""i"":1,""score"":0.9999,""id"":""https://openalex....","[{""id"":""https://openalex.org/keywords/letrozol...",False,None
4,https://openalex.org/W2170318505,Observation of a Narrow Charmoniumlike State i...,Observation of a Narrow Charmoniumlike State i...,We report the observation of a narrow charmoni...,https://doi.org/10.1103/physrevlett.91.262001,2003-12-23,2003,1783,"[""https://openalex.org/W2170318505"",""https://d...",article,...,https://openalex.org/P4310320261,American Physical Society,https://doi.org/10.1103/physrevlett.91.262001,None,None,None,"[{""i"":1,""score"":1,""id"":""https://openalex.org/T...","[{""id"":""https://openalex.org/keywords/kekb"",""d...",False,None

In [8]:
publication['topics'].unique()

array(['[{"i":1,"score":0.9969,"id":"https://openalex.org/T11044","display_name":"Particle Detector Development and Performance","type":"topic"},{"i":1,"score":0.9969,"id":"https://openalex.org/subfields/3106","display_name":"Nuclear and High Energy Physics","type":"subfield"},{"i":1,"score":0.9969,"id":"https://openalex.org/fields/31","display_name":"Physics and Astronomy","type":"field"},{"i":1,"score":0.9969,"id":"https://openalex.org/domains/3","display_name":"Physical Sciences","type":"domain"},{"i":2,"score":0.9969,"id":"https://openalex.org/T10597","display_name":"Nuclear reactor physics and engineering","type":"topic"},{"i":2,"score":0.9969,"id":"https://openalex.org/subfields/2202","display_name":"Aerospace Engineering","type":"subfield"},{"i":2,"score":0.9969,"id":"https://openalex.org/fields/22","display_name":"Engineering","type":"field"},{"i":2,"score":0.9969,"id":"https://openalex.org/domains/3","display_name":"Physical Sciences","type":"domain"},{"i":3,"score":0.9967,"id":"https://openalex.org/T11176","display_name":"Radiation Therapy and Dosimetry","type":"topic"},{"i":3,"score":0.9967,"id":"https://openalex.org/subfields/2740","display_name":"Pulmonary and Respiratory Medicine","type":"subfield"},{"i":3,"score":0.9967,"id":"https://openalex.org/fields/27","display_name":"Medicine","type":"field"},{"i":3,"score":0.9967,"id":"https://openalex.org/domains/4","display_name":"Health Sciences","type":"domain"}]',
       '[{"i":1,"score":0.9999,"id":"https://openalex.org/T10848","display_name":"Advanced Multi-Objective Optimization Algorithms","type":"topic"},{"i":1,"score":0.9999,"id":"https://openalex.org/subfields/1703","display_name":"Computational Theory and Mathematics","type":"subfield"},{"i":1,"score":0.9999,"id":"https://openalex.org/fields/17","display_name":"Computer Science","type":"field"},{"i":1,"score":0.9999,"id":"https://openalex.org/domains/3","display_name":"Physical Sciences","type":"domain"},{"i":2,"score":0.9989,"id":"https://openalex.org/T10100","display_name":"Metaheuristic Optimization Algorithms Research","type":"topic"},{"i":2,"score":0.9989,"id":"https://openalex.org/subfields/1702","display_name":"Artificial Intelligence","type":"subfield"},{"i":2,"score":0.9989,"id":"https://openalex.org/fields/17","display_name":"Computer Science","type":"field"},{"i":2,"score":0.9989,"id":"https://openalex.org/domains/3","display_name":"Physical Sciences","type":"domain"},{"i":3,"score":0.9959,"id":"https://openalex.org/T11975","display_name":"Evolutionary Algorithms and Applications","type":"topic"},{"i":3,"score":0.9959,"id":"https://openalex.org/subfields/1702","display_name":"Artificial Intelligence","type":"subfield"},{"i":3,"score":0.9959,"id":"https://openalex.org/fields/17","display_name":"Computer Science","type":"field"},{"i":3,"score":0.9959,"id":"https://openalex.org/domains/3","display_name":"Physical Sciences","type":"domain"}]',
       '[{"i":1,"score":0.9964,"id":"https://openalex.org/T10272","display_name":"Mental Health Treatment and Access","type":"topic"},{"i":1,"score":0.9964,"id":"https://openalex.org/subfields/3207","display_name":"Social Psychology","type":"subfield"},{"i":1,"score":0.9964,"id":"https://openalex.org/fields/32","display_name":"Psychology","type":"field"},{"i":1,"score":0.9964,"id":"https://openalex.org/domains/2","display_name":"Social Sciences","type":"domain"},{"i":2,"score":0.9924,"id":"https://openalex.org/T13883","display_name":"Child and Adolescent Health","type":"topic"},{"i":2,"score":0.9924,"id":"https://openalex.org/subfields/3600","display_name":"General Health Professions","type":"subfield"},{"i":2,"score":0.9924,"id":"https://openalex.org/fields/36","display_name":"Health Professions","type":"field"},{"i":2,"score":0.9924,"id":"https://openalex.org/domains/4","display_name":"Health Sciences","type":"domain"},{"i":3,"score":0.9919,"id":"https://openalex.org/T10182","display_name":"Child and Adolescent Psychosocial and Emotional Development","type":"topic"},{"i":3,"score":0.9919,"id":"https://openalex.org/subfields/3203","display_name":"Clinical Psychology","type":"subfield"},{"i":3,"score":0.9919,"id":"https://openalex.org/fields/32","display_name":"Psychology","type":"field"},{"i":3,"score":0.9919,"id":"https://openalex.org/domains/2","display_name":"Social Sciences","type":"domain"}]',
       ...,
       '[{"i":1,"score":1,"id":"https://openalex.org/T10048","display_name":"Particle physics theoretical and experimental studies","type":"topic"},{"i":1,"score":1,"id":"https://openalex.org/subfields/3106","display_name":"Nuclear and High Energy Physics","type":"subfield"},{"i":1,"score":1,"id":"https://openalex.org/fields/31","display_name":"Physics and Astronomy","type":"field"},{"i":1,"score":1,"id":"https://openalex.org/domains/3","display_name":"Physical Sciences","type":"domain"},{"i":2,"score":0.9993,"id":"https://openalex.org/T10527","display_name":"High-Energy Particle Collisions Research","type":"topic"},{"i":2,"score":0.9993,"id":"https://openalex.org/subfields/3106","display_name":"Nuclear and High Energy Physics","type":"subfield"},{"i":2,"score":0.9993,"id":"https://openalex.org/fields/31","display_name":"Physics and Astronomy","type":"field"},{"i":2,"score":0.9993,"id":"https://openalex.org/domains/3","display_name":"Physical Sciences","type":"domain"},{"i":3,"score":0.9979,"id":"https://openalex.org/T10224","display_name":"Quantum Chromodynamics and Particle Interactions","type":"topic"},{"i":3,"score":0.9979,"id":"https://openalex.org/subfields/3106","display_name":"Nuclear and High Energy Physics","type":"subfield"},{"i":3,"score":0.9979,"id":"https://openalex.org/fields/31","display_name":"Physics and Astronomy","type":"field"},{"i":3,"score":0.9979,"id":"https://openalex.org/domains/3","display_name":"Physical Sciences","type":"domain"}]',
       '[{"i":1,"score":1,"id":"https://openalex.org/T10048","display_name":"Particle physics theoretical and experimental studies","type":"topic"},{"i":1,"score":1,"id":"https://openalex.org/subfields/3106","display_name":"Nuclear and High Energy Physics","type":"subfield"},{"i":1,"score":1,"id":"https://openalex.org/fields/31","display_name":"Physics and Astronomy","type":"field"},{"i":1,"score":1,"id":"https://openalex.org/domains/3","display_name":"Physical Sciences","type":"domain"},{"i":2,"score":0.9958,"id":"https://openalex.org/T13650","display_name":"Computational Physics and Python Applications","type":"topic"},{"i":2,"score":0.9958,"id":"https://openalex.org/subfields/1702","display_name":"Artificial Intelligence","type":"subfield"},{"i":2,"score":0.9958,"id":"https://openalex.org/fields/17","display_name":"Computer Science","type":"field"},{"i":2,"score":0.9958,"id":"https://openalex.org/domains/3","display_name":"Physical Sciences","type":"domain"},{"i":3,"score":0.9945,"id":"https://openalex.org/T11044","display_name":"Particle Detector Development and Performance","type":"topic"},{"i":3,"score":0.9945,"id":"https://openalex.org/subfields/3106","display_name":"Nuclear and High Energy Physics","type":"subfield"},{"i":3,"score":0.9945,"id":"https://openalex.org/fields/31","display_name":"Physics and Astronomy","type":"field"},{"i":3,"score":0.9945,"id":"https://openalex.org/domains/3","display_name":"Physical Sciences","type":"domain"}]',
       '[{"i":1,"score":0.9996,"id":"https://openalex.org/T11019","display_name":"Image Enhancement Techniques","type":"topic"},{"i":1,"score":0.9996,"id":"https://openalex.org/subfields/1707","display_name":"Computer Vision and Pattern Recognition","type":"subfield"},{"i":1,"score":0.9996,"id":"https://openalex.org/fields/17","display_name":"Computer Science","type":"field"},{"i":1,"score":0.9996,"id":"https://openalex.org/domains/3","display_name":"Physical Sciences","type":"domain"},{"i":2,"score":0.9966,"id":"https://openalex.org/T10036","display_name":"Advanced Neural Network Applications","type":"topic"},{"i":2,"score":0.9966,"id":"https://openalex.org/subfields/1707","display_name":"Computer Vision and Pattern Recognition","type":"subfield"},{"i":2,"score":0.9966,"id":"https://openalex.org/fields/17","display_name":"Computer Science","type":"field"},{"i":2,"score":0.9966,"id":"https://openalex.org/domains/3","display_name":"Physical Sciences","type":"domain"},{"i":3,"score":0.9964,"id":"https://openalex.org/T11659","display_name":"Advanced Image Fusion Techniques","type":"topic"},{"i":3,"score":0.9964,"id":"https://openalex.org/subfields/2214","display_name":"Media Technology","type":"subfield"},{"i":3,"score":0.9964,"id":"https://openalex.org/fields/22","display_name":"Engineering","type":"field"},{"i":3,"score":0.9964,"id":"https://openalex.org/domains/3","display_name":"Physical Sciences","type":"domain"}]'],
      shape=(23630,), dtype=object)

In [ ]:
from tqdm import tqdm

# Set tqdm to work with groupby
tqdm.pandas()

# Group manually with tqdm
print("👥 Grouping authors with progress...")
grouped = []
for work_id, group in tqdm(author.groupby('work_id'), total=author['work_id'].nunique()):
    names = '; '.join(group['display_name'].dropna().unique())
    ids = '; '.join(group['author_id'].dropna().unique())
    grouped.append({
        'work_id': work_id,
        'author_names': names,
        'author_ids': ids
    })

# Convert to DataFrame
grouped_authors = pd.DataFrame(grouped)

# Merge
print("🔗 Merging grouped authors into publications...")
df_final = publication.merge(grouped_authors, on='work_id', how='left')

print("✅ All done, boss.")

👥 Grouping authors with progress...

100%|██████████| 24765/24765 [00:17<00:00, 1378.01it/s]

🔗 Merging grouped authors into publications...
💾 Saving to publication_flat.parquet...
✅ All done, boss.

In [11]:
df_final.shape

(24907, 26)

In [12]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [13]:
df_final.head()

,work_id,title,display_name,abstract,doi,publication_date,publication_year,cited_by_count,ids,type,is_oa,source_display_name,source_id,issn_l,host_organization,host_organization_name,landing_page_url,pdf_url,license,version,topics,keywords,is_retracted,grants,author_names,author_ids
0,https://openalex.org/W2128158076,Geant4—a simulation toolkit,Geant4—a simulation toolkit,None,https://doi.org/10.1016/s0168-9002(03)01368-8,2003-06-21,2003,22300,"[""https://openalex.org/W2128158076"",""https://d...",article,False,Nuclear Instruments and Methods in Physics Res...,https://openalex.org/S145630073,0168-9002,https://openalex.org/P4310320990,Elsevier BV,https://doi.org/10.1016/s0168-9002(03)01368-8,None,None,None,"[{""i"":1,""score"":0.9969,""id"":""https://openalex....","[{""id"":""https://openalex.org/keywords/tracking...",False,None,S. Agostinelli; John E. Allison; B. R. Ko; J. ...,A5019950553; A5102846098; A5009376065; A505619...
1,https://openalex.org/W2125899728,Comparison of Multiobjective Evolutionary Algo...,Comparison of Multiobjective Evolutionary Algo...,"In this paper, we provide a systematic compari...",https://doi.org/10.1162/106365600568202,2000-06-01,2000,5352,"[""https://openalex.org/W2125899728"",""https://d...",article,False,Evolutionary Computation,https://openalex.org/S38677346,1063-6560,https://openalex.org/P4310315718,The MIT Press,https://doi.org/10.1162/106365600568202,None,None,None,"[{""i"":1,""score"":0.9999,""id"":""https://openalex....",null,False,None,Eckart Zitzler; Kalyanmoy Deb; Lothar Thiele,A5031698269; A5088394271; A5060999697
2,https://openalex.org/W2144476887,No health without mental health,No health without mental health,None,https://doi.org/10.1016/s0140-6736(07)61238-0,2007-09-01,2007,3567,"[""https://openalex.org/W2144476887"",""https://d...",review,False,The Lancet,https://openalex.org/S49861241,0140-6736,https://openalex.org/P4310320990,Elsevier BV,https://doi.org/10.1016/s0140-6736(07)61238-0,None,None,None,"[{""i"":1,""score"":0.9964,""id"":""https://openalex....",null,False,None,Martin Prince; Vikram Patel; Shekhar Saxena; M...,A5051774516; A5070156674; A5025675403; A510542...
3,https://openalex.org/W2101881391,A Randomized Trial of Letrozole in Postmenopau...,A Randomized Trial of Letrozole in Postmenopau...,"In hormone-dependent breast cancer, five years...",https://doi.org/10.1056/nejmoa032312,2003-11-06,2003,1803,"[""https://openalex.org/W2101881391"",""https://d...",letter,True,New England Journal of Medicine,https://openalex.org/S62468778,0028-4793,https://openalex.org/P4310320239,Massachusetts Medical Society,https://doi.org/10.1056/nejmoa032312,https://www.nejm.org/doi/pdf/10.1056/NEJMoa032...,None,publishedVersion,"[{""i"":1,""score"":0.9999,""id"":""https://openalex....","[{""id"":""https://openalex.org/keywords/letrozol...",False,None,Paul E. Goss; James N. Ingle; Silvana Martino;...,A5109239396; A5083904553; A5112774196; A507548...
4,https://openalex.org/W2170318505,Observation of a Narrow Charmoniumlike State i...,Observation of a Narrow Charmoniumlike State i...,We report the observation of a narrow charmoni...,https://doi.org/10.1103/physrevlett.91.262001,2003-12-23,2003,1783,"[""https://openalex.org/W2170318505"",""https://d...",article,False,Physical Review Letters,https://openalex.org/S24807848,0031-9007,https://openalex.org/P4310320261,American Physical Society,https://doi.org/10.1103/physrevlett.91.262001,None,None,None,"[{""i"":1,""score"":1,""id"":""https://openalex.org/T...","[{""id"":""https://openalex.org/keywords/kekb"",""d...",False,None,S.-K. Choi; S. L. Olsen; K. Abe; I. Adachi; By...,A5049278896; A5051581351; A5055484840; A510786...

In [14]:
df_final.columns

Index(['work_id', 'title', 'display_name', 'abstract', 'doi',
       'publication_date', 'publication_year', 'cited_by_count', 'ids', 'type',
       'is_oa', 'source_display_name', 'source_id', 'issn_l',
       'host_organization', 'host_organization_name', 'landing_page_url',
       'pdf_url', 'license', 'version', 'topics', 'keywords', 'is_retracted',
       'grants', 'author_names', 'author_ids'],
      dtype='object')

In [16]:
import json

def extract_topic_names(topic_str):
    try:
        topic_list = json.loads(topic_str)
        return '; '.join(set([entry['display_name'] for entry in topic_list if 'display_name' in entry]))
    except:
        return None

print("🧠 Extracting display_name from topics...")
df_final['topic_names'] = df_final['topics'].progress_apply(extract_topic_names)

🧠 Extracting display_name from topics...

100%|██████████| 24907/24907 [00:00<00:00, 40856.93it/s]

In [17]:
df_final.head()

,work_id,title,display_name,abstract,doi,publication_date,publication_year,cited_by_count,ids,type,is_oa,source_display_name,source_id,issn_l,host_organization,host_organization_name,landing_page_url,pdf_url,license,version,topics,keywords,is_retracted,grants,author_names,author_ids,topic_names
0,https://openalex.org/W2128158076,Geant4—a simulation toolkit,Geant4—a simulation toolkit,None,https://doi.org/10.1016/s0168-9002(03)01368-8,2003-06-21,2003,22300,"[""https://openalex.org/W2128158076"",""https://d...",article,False,Nuclear Instruments and Methods in Physics Res...,https://openalex.org/S145630073,0168-9002,https://openalex.org/P4310320990,Elsevier BV,https://doi.org/10.1016/s0168-9002(03)01368-8,None,None,None,"[{""i"":1,""score"":0.9969,""id"":""https://openalex....","[{""id"":""https://openalex.org/keywords/tracking...",False,None,S. Agostinelli; John E. Allison; B. R. Ko; J. ...,A5019950553; A5102846098; A5009376065; A505619...,Engineering; Medicine; Nuclear reactor physics...
1,https://openalex.org/W2125899728,Comparison of Multiobjective Evolutionary Algo...,Comparison of Multiobjective Evolutionary Algo...,"In this paper, we provide a systematic compari...",https://doi.org/10.1162/106365600568202,2000-06-01,2000,5352,"[""https://openalex.org/W2125899728"",""https://d...",article,False,Evolutionary Computation,https://openalex.org/S38677346,1063-6560,https://openalex.org/P4310315718,The MIT Press,https://doi.org/10.1162/106365600568202,None,None,None,"[{""i"":1,""score"":0.9999,""id"":""https://openalex....",null,False,None,Eckart Zitzler; Kalyanmoy Deb; Lothar Thiele,A5031698269; A5088394271; A5060999697,Metaheuristic Optimization Algorithms Research...
2,https://openalex.org/W2144476887,No health without mental health,No health without mental health,None,https://doi.org/10.1016/s0140-6736(07)61238-0,2007-09-01,2007,3567,"[""https://openalex.org/W2144476887"",""https://d...",review,False,The Lancet,https://openalex.org/S49861241,0140-6736,https://openalex.org/P4310320990,Elsevier BV,https://doi.org/10.1016/s0140-6736(07)61238-0,None,None,None,"[{""i"":1,""score"":0.9964,""id"":""https://openalex....",null,False,None,Martin Prince; Vikram Patel; Shekhar Saxena; M...,A5051774516; A5070156674; A5025675403; A510542...,General Health Professions; Child and Adolesce...
3,https://openalex.org/W2101881391,A Randomized Trial of Letrozole in Postmenopau...,A Randomized Trial of Letrozole in Postmenopau...,"In hormone-dependent breast cancer, five years...",https://doi.org/10.1056/nejmoa032312,2003-11-06,2003,1803,"[""https://openalex.org/W2101881391"",""https://d...",letter,True,New England Journal of Medicine,https://openalex.org/S62468778,0028-4793,https://openalex.org/P4310320239,Massachusetts Medical Society,https://doi.org/10.1056/nejmoa032312,https://www.nejm.org/doi/pdf/10.1056/NEJMoa032...,None,publishedVersion,"[{""i"":1,""score"":0.9999,""id"":""https://openalex....","[{""id"":""https://openalex.org/keywords/letrozol...",False,None,Paul E. Goss; James N. Ingle; Silvana Martino;...,A5109239396; A5083904553; A5112774196; A507548...,Medicine; Genetics; Breast Cancer Treatment St...
4,https://openalex.org/W2170318505,Observation of a Narrow Charmoniumlike State i...,Observation of a Narrow Charmoniumlike State i...,We report the observation of a narrow charmoni...,https://doi.org/10.1103/physrevlett.91.262001,2003-12-23,2003,1783,"[""https://openalex.org/W2170318505"",""https://d...",article,False,Physical Review Letters,https://openalex.org/S24807848,0031-9007,https://openalex.org/P4310320261,American Physical Society,https://doi.org/10.1103/physrevlett.91.262001,None,None,None,"[{""i"":1,""score"":1,""id"":""https://openalex.org/T...","[{""id"":""https://openalex.org/keywords/kekb"",""d...",False,None,S.-K. Choi; S. L. Olsen; K. Abe; I. Adachi; By...,A5049278896; A5051581351; A5055484840; A510786...,Particle physics theoretical and experimental ...

In [18]:
print("💾 Saving to publication_flat.parquet...")
df_final.to_parquet("publication.parquet", index=False)

💾 Saving to publication_flat.parquet...

In [20]:
final = pd.read_parquet("search-application\data\publication.parquet")
final.columns

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\prans\AppData\Local\Temp\ipykernel_15376\281169801.py:1: SyntaxWarning: invalid escape sequence '\d'
  final = pd.read_parquet("search-application\data\publication.parquet")

Index(['work_id', 'title', 'display_name', 'abstract', 'doi',
       'publication_date', 'publication_year', 'cited_by_count', 'ids', 'type',
       'is_oa', 'source_display_name', 'source_id', 'issn_l',
       'host_organization', 'host_organization_name', 'landing_page_url',
       'pdf_url', 'license', 'version', 'topics', 'keywords', 'is_retracted',
       'grants', 'author_names', 'author_ids', 'topic_names'],
      dtype='object')